; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
boards_dir = boards/nordicnrf52
;src_dir = bluefruit_ex

[env:nicenano]
platform = nordicnrf52
board = nicenano
framework = arduino
board_build.variants_dir = variants
;board_build.variant = promicro
;board_build.variant = mesh2
board_build.variant = nicenano
platform_packages = 
    framework-arduinoadafruitnrf52
upload_protocol = nrfutil
lib_deps = 
	https://github.com/adafruit/Adafruit_nRF52_Arduino
	jgromes/RadioLib@^7.3.0
	mikalhart/TinyGPSPlus
	adafruit/SdFat - Adafruit Fork@^2.3.103
extra_scripts = pre:extra_scripts.py
build_flags = -DCONFIG_NFCT_PINS_AS_GPIO
check_tool = cppcheck
check_flags = --enable=all

[env:tx_test]
platform = nordicnrf52
board = nicenano
framework = arduino
board_build.variants_dir = variants
board_build.variant = mesh2
platform_packages = 
    framework-arduinoadafruitnrf52
upload_protocol = nrfutil
lib_deps = 
	https://github.com/adafruit/Adafruit_nRF52_Arduino
	jgromes/RadioLib@^7.3.0
	mikalhart/TinyGPSPlus
extra_scripts = pre:extra_scripts.py
build_flags = -DCONFIG_NFCT_PINS_AS_GPIO -DNODE_ID=2
build_src_filter = -<src/> +<../tx_test/>
check_tool = cppcheck
check_flags = --enable=all
