; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
boards_dir = boards/nordicnrf52

[env:nicenano]
platform = nordicnrf52
board = nicenano
framework = arduino
board_build.variants_dir = variants
;board_build.variant = promicro
board_build.variant = mesh2
platform_packages = 
    framework-arduinoadafruitnrf52
upload_protocol = nrfutil
lib_deps = 
	https://github.com/adafruit/Adafruit_nRF52_Arduino
	adafruit/Adafruit SSD1306@^2.5.14
	mikalhart/TinyGPSPlus@^1.1.0
	jgromes/RadioLib@^7.3.0
;	jaimi5/LoRaMesher@^0.0.11
extra_scripts = pre:extra_scripts.py
